using UnityEngine;

public class Player_DashState : EntityState
{

    private float originalGravityScale;
    private int dashDir;
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    public Player_DashState(Player player, StateMachine stateMachine, string animBoolName) : base(player, stateMachine, animBoolName)
    {
    }

    public override void Enter()
    {
        base.Enter();
        dashDir = player.moveInput.x != 0 ? ((int)player.moveInput.x) : player.facingDiraction;
        stateTimer = player.dashDuration;
        originalGravityScale = rb.gravityScale;
        rb.gravityScale = 0;
    }

    public override void Update()
    {
        base.Update();
        CancleDashIfNeeded();
        player.SetVelocity(player.dashSpeed * dashDir, 0);

        if (stateTimer < 0)
        {
            if (player.groundDetected)
            {
                stateMachine.changeState(player.idleState);
            }
            else
            {
                stateMachine.changeState(player.fallState);
            }
        }
    }

    public override void Exit()
    {
        base.Exit();
        player.SetVelocity(0, 0);
        rb.gravityScale = originalGravityScale;
    }

    private void CancleDashIfNeeded()
    {
        if (player.wallDetected)
        {
            if (player.groundDetected)
            {
                stateMachine.changeState(player.idleState);
            }
            else
            {
                stateMachine.changeState(player.wallSlideState);
            }
        }
    }
}
